### ISSUE TITLE
Funkytunes disabled in FDroid :(

### ISSUE THREAD

**Issue by funkyg** [funkyg/funkytunes#11]
https://f-droid.org/wiki/page/com.github.funkyg.funkytunes

https://gitlab.com/fdroid/fdroiddata/issues/728

Maybe we have to move back to Github releases and own update checker :/

**Comment by gjedeer** [comment]
I'm not sure why I did it but: https://github.com/gjedeer/fdroid-repo/blob/master/README.md

**Comment by funkyg** [comment]
Wow youre fast. They are already discussing enabling it, so i would just wait for their decision. If they decide against it, having a seperate fdroid repo might be a good idea. But it also might be too complicated to set up, dunno.

https://gitlab.com/fdroid/fdroiddata/merge_requests/2237

**Comment by gjedeer** [comment]
I hope they decide to include it in F-Droid again. It's strange to see them being scared of including an app because it may be used to commit a crime while hosting csploit is perfectly fine. Looks more like Google behavior than that of an independent project. I can't blame them but it sucks.

About the separate repo, if there was an easy way to scan a QR code inside F-Droid and have the repo added, that would be awesome. It's a bit complicated as it is, I agree.

**Comment by funkyg** [comment]
They [suggested to replace the charts with a list of creative commons licensed music](http://freemusicarchive.org/music/charts/this-month/?chart=interest). See my comment there.

But i dont really like to show cc music that no one knows. I think the best option is distributing the apk ourselves, with an integrated updater. Same thing popcorn time is doing.

**Comment by gjedeer** [comment]
Yeah, that would suck (btw, idea for an alternative source of top100 albums: https://thepiratebay.org/top/101 )

Could you make the auto updater an option that can be disabled on build-time? It makes perfect sense for a lay person to use the autoupdater but personally I'd rather not use it.

**Comment by funkyg** [comment]
Ah thats really cool, because it guarantees that the album is actually available for download. Right now a lot of albums wont even play. Only problem is that those albums arent clearly tagged with artist, album name and cover.

For the update check, i would just show a dialog when a new version is available, with a link to the download page (so no automatic update). We could also add a setting to disable update checks. Does that sound good?

**Comment by gjedeer** [comment]
For the update checks: sounds okay, though Github API doesn't return any releases - https://api.github.com/repos/funkyg/funkytunes/releases/latest and https://api.github.com/repos/funkyg/funkytunes/releases - wondering if it's because

>  Draft releases and prereleases are not returned by this endpoint.

For TPB as source: I opened top 10 albums and 6 out of 10 had something like this in the description:
```
Artist : Future
Album : FUTURE
```

```
Title: Despacito (feat. Daddy Yankee)
Artist: Luis Fonsi
Album: Despacito (feat. Daddy Yankee) - Single
```

The downside is: lots of HTTP requests do find out the descriptions.

**Comment by funkyg** [comment]
looks like they werent listed as releases because they didnt have a title, i set that and it works now. I reverted 682297bcfed7b1d10a0a72feaf644d4aa364e05c to enable the update check again. Should i also add a setting to disable update checks?

And scraping pirate bay like that sounds extremely fragile, i dont like it at all. It also doesnt have any covers. Maybe we could search the pirate bay title via discogs, and take the first result from there? No idea how well that would work though.

**Comment by gjedeer** [comment]
Maybe the setting is not needed now.

TPB: I entered a few titles manually (without any kind of sanitization, with [MP3_320] etc) and it worked good. Should we move TPB discussion to #1 maybe?

**Comment by funkyg** [comment]
Yeah #1 is a better place.

Regarding downloads, i will just put the previous download button back in (pointing to github releases), and upload the latest apk on github releases.

**Comment by gjedeer** [comment]
Maybe point it to the latest release? 'html_url' key in /releases/latest JSON.

**Comment by funkyg** [comment]
im just pointing it to https://github.com/funkyg/funkytunes/releases/latest

**Comment by gjedeer** [comment]
Any idea wtf is going on with fdroid? Looks like it's gone again but couldn't find any comments on it in fdroiddata...

**Comment by funkyg** [comment]
apparently they moved it to the archive, so its only available if you enable that in the settings. And they dont build any new versions. i guess because they arent sure if its legal?

**Comment by IzzySoft** [comment]
I've just stumbled upon this issue checking for the status of the project (it's [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.github.funkyg.funkytunes) currently). Checking the history of the metadata file in F-Droid I wonder if the `Archive Policy:0 versions` (which is responsible for the fact your app is only available in archive) wasn't left there in error after clarifying the status.

Is your project still alive, @funkyg (there was no commit for about 1.5 years, hence I wonder)? Then I could see whether we bring it back to the main repo.

**Comment by gjedeer** [comment]
Not him but I will answer: I'm not working on it, I guess funkyg isn't either. F-Droid wasn't too keen on keeping it in the main repo -> it doesn't have users -> not really maintained. Hell, noone noticed that the skytorrents scraper isn't working for a long long time and all it takes to fix it is to change the TLD (.in to .lol)

**Comment by IzzySoft** [comment]
@gjedeer thanks for your answer! There was no "bad intent" behind the actions at F-Droid – we must of course take care our content is legit, and probably someone was rather "extra-careful". Nobody noticed the archive policy, though, it seems – like nobody noticed that scraper to be "out of sync with reality".

So maybe I add a notice in my repo that your app currently isn't *actively* maintained (meaning no active development – but issues are answered and PRs would be processed). That OK with you? Guess there's no need anymore for action on the main repo then – but of course I could try to get at least the latest version back to the main repo if you wish. That'd just need to update the archive policy from 0 to 1 (1 version in main, rest in archive).
