### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by funkyg** [funkyg/funkytunes#12]
It would be good to have some automated builds to make sure nothing breaks. Can anyone recommend one of these?

https://github.com/integrations/feature/continuous-integration

Should be easy to configure, handle lint and unit tests, and be free.

**Comment by gjedeer** [comment]
Travis is easy, I never used it with Android but it looks okay too https://docs.travis-ci.com/user/languages/android/

**Comment by funkyg** [comment]
Ive added buddybuild for ci. You should have an invitation email
