### ISSUE TITLE
throttle requests to discogs api

### ISSUE THREAD

**Issue by gjedeer** [funkyg/funkytunes#17]
App is sending requests more often than needed, discogs returns 429 sometimes. Once every 500 ms would be enough.

**Comment by funkyg** [comment]
i guess thats for the search? because it sends requests whenever the query string changes. Agree that 500 ms would be enough. Or we can make it so the user has to press enter before it is sent.

**Comment by gjedeer** [comment]
The current incremental search is awesome so my vote goes to just throttling/debouncing.

**Comment by funkyg** [comment]
what do you mean by debouncing?

**Comment by gjedeer** [comment]
Silly term for throttling from [javascript world ](https://github.com/cowboy/jquery-throttle-debounce)

**Comment by funkyg** [comment]
oh i see. Luckily i dont use any javascript :D
