### ISSUE TITLE
How to close the app?

### ISSUE THREAD

**Issue by gjedeer** [funkyg/funkytunes#20]
I always force-closed the app by holding the back button, but the typical user had no idea how to quit when the music was already playing. An exit option or something would be useful.

**Comment by funkyg** [comment]
good idea, fixed :)

**Comment by funkyg** [comment]
on second thought, it would probably be good to have a close button on the notification. i will add that too.

**Comment by gjedeer** [comment]
My "reference user" had no idea there was a notification until i showed that to them. Maybe don't remove the new menu option?

**Comment by funkyg** [comment]
yeah that makes sense
