### ISSUE TITLE
New release with skytorrents

### ISSUE THREAD

**Issue by sim6** [funkyg/funkytunes#24]
Hello,

Please, could you create a new release with skytorrents (#18).

Before it, and the current f-droid.org version, doesn't work properly and generates a bad impression.

Thanks.

**Comment by gjedeer** [comment]
@sim6 are you saying it's back in f-droid now?

**Comment by funkyg** [comment]
released 0.1.2 ;)

and yes it looks like funkytunes was enabled in fdroid (but i cant find it when i serach in the app)
https://gitlab.com/fdroid/fdroiddata/merge_requests/2237
https://f-droid.org/wiki/page/com.github.funkyg.funkytunes

**Comment by sim6** [comment]
Thanks
