### ISSUE TITLE
Last version has wrong versionCode

### ISSUE THREAD

**Issue by IzzySoft** [funkyg/funkytunes#29]
Just a note: Looks like you forgot incrementing the `versionCode` of the latest APK in `releases/`:

    com.github.funkyg.funkytunes_0.1.1*
    package: name='com.github.funkyg.funkytunes' versionCode='2' versionName='0.1.1' platformBuildVersionName='7.1.1'
    com.github.funkyg.funkytunes_0.1.2*
    package: name='com.github.funkyg.funkytunes' versionCode='2' versionName='0.1.2' platformBuildVersionName='7.1.1'

There cannot be two `.apk` files with the same version code in a repo, thus todays update [here](https://apt.izzysoft.de/fdroid/index/apk/com.github.funkyg.funkytunes) failed (had to manually remove the previous version to get the new one in).

Could you please ensure the increment for future versions? Thanks!

**Comment by funkyg** [comment]
oops... 

fixed it with a new version

**Comment by IzzySoft** [comment]
Confirmed, repo updated without manual intervention :smile_cat: Thanks!
