### ISSUE TITLE
Submit to F-droid?

### ISSUE THREAD

**Issue by ghost** [funkyg/funkytunes#3]
Sounds great, especially the "fully open source" part :) Please consider submitting the project for inclusion in the F-droid repository!

**Comment by funkyg** [comment]
Good idea, i will submit it :)

**Comment by funkyg** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2202

**Comment by funkyg** [comment]
done :)
https://f-droid.org/repository/browse/?fdfilter=funkytunes&fdid=com.github.funkyg.funkytunes

**Comment by ghost** [comment]
It has been disabled due to legal concerns, which is understandable. You could make it legal easily by requiring the user to input a source (ie from which tracker to get the files). This can also improve the compatibility with other trackers... and down the road maybe with private trackers?
