### ISSUE TITLE
No download nothing

### ISSUE THREAD

**Issue by sim6** [funkyg/funkytunes#31]
The version 0.1.2 works to me but the last version 0.1.3 doesn't download nothing.

**Comment by funkyg** [comment]
works fine for me. Can you try to exit  the app from the menu, or restart your phone?

**Comment by sim6** [comment]
I tried to exit the app but doesn't work. But after reboot the phone now it works.

**Comment by gjedeer** [comment]
If you keep having this issue please post logcat.

On 8 June 2017 08:13:19 CEST, "Simó Albert i Beltran" <notifications@github.com> wrote:
>The version 0.1.2 works to me but the last version 0.1.3 doesn't
>download nothing.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/funkyg/funkytunes/issues/31

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
