### ISSUE TITLE
Pause on phone call

### ISSUE THREAD

**Issue by sim6** [funkyg/funkytunes#33]
Please, could you pause on phone call?

Thanks.

**Comment by gjedeer** [comment]
@sim6  mind testing funkyg's fix for your issue? APK, if you don't want to build: https://downloads.buddybuild.com/api/download/download-apk?buildID=593a89446d49e50001fc9704&application_variant=debug

**Comment by sim6** [comment]
I think buddybuild isn't open source :( so I complied it and works, thank you very much!

**Comment by gjedeer** [comment]
Hmm, on Android 7 when you install it for the first time (not upgrade) it's asking for permission to "make phone calls". Is there a more granular permission maybe? I've never seen other media player ask for that and  guess VLC, for example, supports that.

**Comment by funkyg** [comment]
youre right, i just found this info: https://developer.android.com/guide/topics/media-apps/volume-and-earphones.html

will try to implement that.

**Comment by funkyg** [comment]
okay i implemented that in a6bea9f04b537a3b4ac5c76cedf368bae9e42373

**Comment by gjedeer** [comment]
Nice. Maybe remove the telephony permission too?

**Comment by funkyg** [comment]
i did that in the previous commint ;)
