### ISSUE TITLE
Song selection

### ISSUE THREAD

**Issue by dimqua** [funkyg/funkytunes#38]
Currently, you can't select the song you want to play first, and it's imposible to switch between album's songs freely.

Please add a possibility to choose the song manually.

**Comment by gjedeer** [comment]
Did you try 0.2.0?

Long story short: what you're describing is possible but the user interface wasn't giving any indication the song is switched, and if the torrent was slow it gave the impression you can't switch a song. User interface for switching songs is improved in 0.2.0.

**Comment by dimqua** [comment]
Yes, from F-Droid, but I can't select the song №3 and then №6, for example, and skip the song №1 compeltly. But sequential order (1,2,3,...) works fine.

**Comment by gjedeer** [comment]
Ooh, like building a playlist.

On July 5, 2017 4:45:27 PM GMT+02:00, dimqua <notifications@github.com> wrote:
>Yes, from F-Droid, but I can't select the song №3 and then №6, for
>example, and skip the song №1 compeltly. But sequential order
>(1,2,3,...) works fine.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/funkyg/funkytunes/issues/38#issuecomment-313124962

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
