### ISSUE TITLE
update available

### ISSUE THREAD

**Issue by gjedeer** [funkyg/funkytunes#4]
I'm getting "update available" notifications that take me to the Releases page on github. After downloading the only release that's shown there, I still get the update notification.

**Comment by funkyg** [comment]
Sounds like something is wrong with the update checks. I will make a new version that removes the update checks (handled by FDroid now).

**Comment by gjedeer** [comment]
It's on f-droid now? I can not find it but nice, i will switch.

**Comment by funkyg** [comment]
https://f-droid.org/repository/browse/?fdfilter=funkytunes&fdid=com.github.funkyg.funkytunes

**Comment by gjedeer** [comment]
Thanks. The F-Droid version indeed doesn't show that popup but shows "Github Repository Missing" popup instead and proposes to open gitlab mirror.

**Comment by gjedeer** [comment]
Also: stuck at "loading torrent" no matter what album I choose, checked in catlog and there was a bunch of 404 errors. Do you need a log or are you aware of the problem?

**Comment by funkyg** [comment]
Lots of albums are listed by itunes/discogs, but cant be found on pirate bay :(

The search is pretty basic (see readme), but i dont know how else to get the info (also check issue #1)

**Comment by blackhole0sun** [comment]
No apk download on f-droid, no apk download here at github!!!! 
But there is nowhere any infomation about the download, nothing like "under construction" or else.

**Comment by blackhole0sun** [comment]
No apk download on f-droid, no apk download here at github!!!! 
But there is nowhere any infomation about the download, nothing like "under construction" or else.

**Comment by blackhole0sun** [comment]
No apk download on f-droid, no apk download here at github!!!! 
But there is nowhere any infomation about the download, nothing like "under construction" or else.
