### ISSUE TITLE
APK missing from latest release

### ISSUE THREAD

**Issue by IzzySoft** [funkyg/funkytunes#41]
Looks like you forgot to attach the `.apk` to the latest release. Could you please fill that gap? Thanks!

**Comment by gjedeer** [comment]
I don't have the signing key and @funkyg seems to be offline

**Comment by IzzySoft** [comment]
Oh. That explains. Sad to hear this! I hope his "offline-ness" won't be for too long (or even permanent) :scream: Shall we leave this issue open as a reminder on his return?

Thanks for the information, btw!

**Comment by funkyg** [comment]
sorry i was on vacation. will make a release and send you the signing key @gjedeer

**Comment by IzzySoft** [comment]
Thanks a lot, @funkyg !

**Comment by IzzySoft** [comment]
PS: Please don't forget to increade `versionCode` with each new release. The last two versions both have it set to `6`, which make them the same version for Android.
