### ISSUE TITLE
ISP Blocking

### ISSUE THREAD

**Issue by ghost** [funkyg/funkytunes#7]
I live on France and ISPs are blocking the mirror toi are using. It makes me really sad because I can't invest in a VPN and using a proxy with mobile data is a pain...
Here are some that aren't blocked :
- pirateproxy.cc
- pirateportal.xyz

**Comment by gjedeer** [comment]
Either theproxypirate.pw is blocked everywhere I tested or it's dead. I checked on several servers in different countries with `dig a theproxypirate.pw` and never returned any records. Maybe the domain is seized?

**Comment by gjedeer** [comment]
I've built a version with Pirate Bay URL changed to pirateproxy.cc and this works beautifully. @AnotherJavaCoder if you'd like to try and don't want to compile, https://f.gdr.name/apk/funkytunes-test.apk

**Comment by ghost** [comment]
Seems to work very well here even if there is a lot of "No matching torrent found". I think this pull request solve this issue completly! 👍 I will wait for it to be bull into the main repo to close it.
